# Standard properties
# -------------------

logging.file.path: /AppData_Java11/JobVacanciesApp/log-files
logging.file.name: /AppData_Java11/JobVacanciesApp/log-files/jobVacanciesApp.log
logging.logback.rollingpolicy.file-name-pattern: /AppData_Java11/JobVacanciesApp/log-files/jobVacanciesApp.%d{yyyy-MM-dd}.%i.log

# Ad-hoc properties
# -----------------

jobvacanciesapp.authUserCurriculumFilesPath: /AppData_Java11/JobVacanciesApp/auth-user-curriculum-files/
jobvacanciesapp.authUserEntityQueryFilesPath: /AppData_Java11/JobVacanciesApp/auth-user-entity-query-files/
jobvacanciesapp.jobCompanyLogosPath: /AppData_Java11/JobVacanciesApp/job-company-logos/
